import turtle as t
import time as time
t.title("My Turtile Program")
t.circle(50)
t.begin_fill()
t.circle(40)
t.end_fill()
t.pen(fillcolor="red")
t.right(90)
t.circle(50)
t.begin_fill()
t.circle(40)
t.end_fill()
t.right(90)
t.circle(50)
t.pen(fillcolor="green")
t.begin_fill()
t.circle(40)
t.end_fill()
t.right(90)
t.pen(fillcolor="blue")
t.begin_fill()
t.end_fill()
t.circle(50)
t.begin_fill()
t.circle(40)
t.end_fill()
time.sleep(5)